module.exports = [
  {
    "city": "Kyiv", 
    "lat": "50.4500", 
    "lng": "30.5236", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyiv, Misto", 
    "capital": "primary", 
    "population": "2963199", 
    "population_proper": "2963199"
  }, 
  {
    "city": "Kharkiv", 
    "lat": "50.0000", 
    "lng": "36.2292", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kharkivs’ka Oblast’", 
    "capital": "admin", 
    "population": "1446107", 
    "population_proper": "1446107"
  }, 
  {
    "city": "Odesa", 
    "lat": "46.4775", 
    "lng": "30.7326", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Odes’ka Oblast’", 
    "capital": "admin", 
    "population": "1017699", 
    "population_proper": "1017699"
  }, 
  {
    "city": "Dnipro", 
    "lat": "48.4500", 
    "lng": "34.9833", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "admin", 
    "population": "1002111", 
    "population_proper": "1002111"
  }, 
  {
    "city": "Donetsk", 
    "lat": "48.0089", 
    "lng": "37.8042", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "admin", 
    "population": "929063", 
    "population_proper": "929063"
  }, 
  {
    "city": "Zaporizhzhia", 
    "lat": "47.8378", 
    "lng": "35.1383", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zaporiz’ka Oblast’", 
    "capital": "admin", 
    "population": "741717", 
    "population_proper": "741717"
  }, 
  {
    "city": "Lviv", 
    "lat": "49.8419", 
    "lng": "24.0315", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "L’vivs’ka Oblast’", 
    "capital": "admin", 
    "population": "724314", 
    "population_proper": "724314"
  }, 
  {
    "city": "Kryvyi Rih", 
    "lat": "47.9086", 
    "lng": "33.3433", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "minor", 
    "population": "629695", 
    "population_proper": "629695"
  }, 
  {
    "city": "Mykolaiv", 
    "lat": "46.9667", 
    "lng": "32.0000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Mykolayivs’ka Oblast’", 
    "capital": "admin", 
    "population": "498748", 
    "population_proper": "498748"
  }, 
  {
    "city": "Mariupol", 
    "lat": "47.1306", 
    "lng": "37.5639", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "449498", 
    "population_proper": "449498"
  }, 
  {
    "city": "Sevastopol", 
    "lat": "44.6000", 
    "lng": "33.5333", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Sevastopol’, Misto", 
    "capital": "admin", 
    "population": "428753", 
    "population_proper": "428753"
  }, 
  {
    "city": "Luhansk", 
    "lat": "48.5833", 
    "lng": "39.3333", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "admin", 
    "population": "417990", 
    "population_proper": "417990"
  }, 
  {
    "city": "Vinnytsia", 
    "lat": "49.2372", 
    "lng": "28.4672", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Vinnyts’ka Oblast’", 
    "capital": "admin", 
    "population": "371855", 
    "population_proper": "371855"
  }, 
  {
    "city": "Makiivka", 
    "lat": "48.0556", 
    "lng": "37.9611", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "347376", 
    "population_proper": "347376"
  }, 
  {
    "city": "Simferopol", 
    "lat": "44.9484", 
    "lng": "34.1000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Krym, Avtonomna Respublika", 
    "capital": "admin", 
    "population": "341799", 
    "population_proper": "341799"
  }, 
  {
    "city": "Poltava", 
    "lat": "49.5744", 
    "lng": "34.5686", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Poltavs’ka Oblast’", 
    "capital": "admin", 
    "population": "317847", 
    "population_proper": "286588"
  }, 
  {
    "city": "Chernihiv", 
    "lat": "51.4939", 
    "lng": "31.2947", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Chernihivs’ka Oblast’", 
    "capital": "admin", 
    "population": "294522", 
    "population_proper": "294522"
  }, 
  {
    "city": "Kherson", 
    "lat": "46.6333", 
    "lng": "32.6000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Khersons’ka Oblast’", 
    "capital": "admin", 
    "population": "291428", 
    "population_proper": "291428"
  }, 
  {
    "city": "Cherkasy", 
    "lat": "49.4444", 
    "lng": "32.0597", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Cherkas’ka Oblast’", 
    "capital": "admin", 
    "population": "276360", 
    "population_proper": "276360"
  }, 
  {
    "city": "Khmelnytskyi", 
    "lat": "49.4200", 
    "lng": "27.0000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Khmel’nyts’ka Oblast’", 
    "capital": "admin", 
    "population": "274176", 
    "population_proper": "274176"
  }, 
  {
    "city": "Zhytomyr", 
    "lat": "50.2544", 
    "lng": "28.6578", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zhytomyrs’ka Oblast’", 
    "capital": "admin", 
    "population": "266936", 
    "population_proper": "266936"
  }, 
  {
    "city": "Chernivtsi", 
    "lat": "48.2908", 
    "lng": "25.9344", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Chernivets’ka Oblast’", 
    "capital": "admin", 
    "population": "266550", 
    "population_proper": "266550"
  }, 
  {
    "city": "Sumy", 
    "lat": "50.9068", 
    "lng": "34.7992", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Sums’ka Oblast’", 
    "capital": "admin", 
    "population": "265758", 
    "population_proper": "265758"
  }, 
  {
    "city": "Horlivka", 
    "lat": "48.3336", 
    "lng": "38.0925", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "minor", 
    "population": "256714", 
    "population_proper": "256714"
  }, 
  {
    "city": "Rivne", 
    "lat": "50.6197", 
    "lng": "26.2514", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Rivnens’ka Oblast’", 
    "capital": "admin", 
    "population": "245630", 
    "population_proper": "245630"
  }, 
  {
    "city": "Ivano-Frankivsk", 
    "lat": "48.9228", 
    "lng": "24.7106", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Ivano-Frankivs’ka Oblast’", 
    "capital": "admin", 
    "population": "236602", 
    "population_proper": "236602"
  }, 
  {
    "city": "Kamianske", 
    "lat": "48.5076", 
    "lng": "34.6132", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "minor", 
    "population": "235066", 
    "population_proper": "235066"
  }, 
  {
    "city": "Kremenchuk", 
    "lat": "49.0775", 
    "lng": "33.4239", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Poltavs’ka Oblast’", 
    "capital": "minor", 
    "population": "234073", 
    "population_proper": "234073"
  }, 
  {
    "city": "Kropyvnytskyi", 
    "lat": "48.5103", 
    "lng": "32.2667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kirovohrads’ka Oblast’", 
    "capital": "admin", 
    "population": "227413", 
    "population_proper": "227413"
  }, 
  {
    "city": "Ternopil", 
    "lat": "49.5667", 
    "lng": "25.6000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Ternopil’s’ka Oblast’", 
    "capital": "admin", 
    "population": "218653", 
    "population_proper": "218653"
  }, 
  {
    "city": "Lutsk", 
    "lat": "50.7478", 
    "lng": "25.3244", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Volyns’ka Oblast’", 
    "capital": "admin", 
    "population": "216505", 
    "population_proper": "216505"
  }, 
  {
    "city": "Bila Tserkva", 
    "lat": "49.7956", 
    "lng": "30.1167", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyivs’ka Oblast’", 
    "capital": "minor", 
    "population": "208944", 
    "population_proper": "208944"
  }, 
  {
    "city": "Kramatorsk", 
    "lat": "48.7208", 
    "lng": "37.5556", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "159445", 
    "population_proper": "159445"
  }, 
  {
    "city": "Melitopol", 
    "lat": "46.8333", 
    "lng": "35.3667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zaporiz’ka Oblast’", 
    "capital": "minor", 
    "population": "154992", 
    "population_proper": "154992"
  }, 
  {
    "city": "Sievierodonetsk", 
    "lat": "48.9500", 
    "lng": "38.4833", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "minor", 
    "population": "150000", 
    "population_proper": "150000"
  }, 
  {
    "city": "Drohobych", 
    "lat": "49.3500", 
    "lng": "23.5000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "L’vivs’ka Oblast’", 
    "capital": "minor", 
    "population": "124269", 
    "population_proper": "79406"
  }, 
  {
    "city": "Khrustalnyi", 
    "lat": "48.1214", 
    "lng": "38.9453", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "124000", 
    "population_proper": "124000"
  }, 
  {
    "city": "Uzhhorod", 
    "lat": "48.6239", 
    "lng": "22.2950", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zakarpats’ka Oblast’", 
    "capital": "admin", 
    "population": "114897", 
    "population_proper": "114897"
  }, 
  {
    "city": "Berdiansk", 
    "lat": "46.7598", 
    "lng": "36.7845", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zaporiz’ka Oblast’", 
    "capital": "minor", 
    "population": "114205", 
    "population_proper": "114205"
  }, 
  {
    "city": "Sloviansk", 
    "lat": "48.8700", 
    "lng": "37.6250", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "113196", 
    "population_proper": "113196"
  }, 
  {
    "city": "Nikopol", 
    "lat": "47.5772", 
    "lng": "34.3575", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "minor", 
    "population": "112102", 
    "population_proper": "112102"
  }, 
  {
    "city": "Yevpatoriia", 
    "lat": "45.2000", 
    "lng": "33.3583", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Krym, Avtonomna Respublika", 
    "capital": "", 
    "population": "106158", 
    "population_proper": "106158"
  }, 
  {
    "city": "Pavlohrad", 
    "lat": "48.5200", 
    "lng": "35.8700", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "minor", 
    "population": "106082", 
    "population_proper": "106082"
  }, 
  {
    "city": "Alchevsk", 
    "lat": "48.4672", 
    "lng": "38.7983", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "minor", 
    "population": "105398", 
    "population_proper": "105398"
  }, 
  {
    "city": "Konotop", 
    "lat": "51.2369", 
    "lng": "33.2027", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Sums’ka Oblast’", 
    "capital": "minor", 
    "population": "103547", 
    "population_proper": "91798"
  }, 
  {
    "city": "Brovary", 
    "lat": "50.5114", 
    "lng": "30.7903", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyivs’ka Oblast’", 
    "capital": "minor", 
    "population": "102856", 
    "population_proper": "102856"
  }, 
  {
    "city": "Kamianets-Podilskyi", 
    "lat": "48.6806", 
    "lng": "26.5806", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Khmel’nyts’ka Oblast’", 
    "capital": "minor", 
    "population": "100462", 
    "population_proper": "100462"
  }, 
  {
    "city": "Lysychansk", 
    "lat": "48.9169", 
    "lng": "38.4306", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "96161", 
    "population_proper": "96161"
  }, 
  {
    "city": "Dovzhansk", 
    "lat": "48.0846", 
    "lng": "39.6516", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "minor", 
    "population": "95153", 
    "population_proper": "95153"
  }, 
  {
    "city": "Mukacheve", 
    "lat": "48.4414", 
    "lng": "22.7136", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zakarpats’ka Oblast’", 
    "capital": "minor", 
    "population": "86257", 
    "population_proper": "86257"
  }, 
  {
    "city": "Uman", 
    "lat": "48.7500", 
    "lng": "30.2167", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Cherkas’ka Oblast’", 
    "capital": "minor", 
    "population": "82762", 
    "population_proper": "82762"
  }, 
  {
    "city": "Yalta", 
    "lat": "44.4994", 
    "lng": "34.1553", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Krym, Avtonomna Respublika", 
    "capital": "", 
    "population": "79458", 
    "population_proper": "79458"
  }, 
  {
    "city": "Yenakiieve", 
    "lat": "48.2311", 
    "lng": "38.2053", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "79348", 
    "population_proper": "79348"
  }, 
  {
    "city": "Shostka", 
    "lat": "51.8657", 
    "lng": "33.4766", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Sums’ka Oblast’", 
    "capital": "minor", 
    "population": "76788", 
    "population_proper": "76788"
  }, 
  {
    "city": "Berdychiv", 
    "lat": "49.8919", 
    "lng": "28.6000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zhytomyrs’ka Oblast’", 
    "capital": "minor", 
    "population": "76229", 
    "population_proper": "76229"
  }, 
  {
    "city": "Bakhmut", 
    "lat": "48.6044", 
    "lng": "38.0067", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "minor", 
    "population": "75798", 
    "population_proper": "75798"
  }, 
  {
    "city": "Stakhanov", 
    "lat": "48.5472", 
    "lng": "38.6361", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "75745", 
    "population_proper": "75745"
  }, 
  {
    "city": "Nizhyn", 
    "lat": "51.0500", 
    "lng": "31.9000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Chernihivs’ka Oblast’", 
    "capital": "minor", 
    "population": "73283", 
    "population_proper": "73283"
  }, 
  {
    "city": "Kostiantynivka", 
    "lat": "48.5333", 
    "lng": "37.7167", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "72888", 
    "population_proper": "72888"
  }, 
  {
    "city": "Izmail", 
    "lat": "45.3500", 
    "lng": "28.8333", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Odes’ka Oblast’", 
    "capital": "minor", 
    "population": "71594", 
    "population_proper": "71594"
  }, 
  {
    "city": "Novomoskovsk", 
    "lat": "48.6328", 
    "lng": "35.2239", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "minor", 
    "population": "70749", 
    "population_proper": "70749"
  }, 
  {
    "city": "Nova Kakhovka", 
    "lat": "46.7667", 
    "lng": "33.3667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Khersons’ka Oblast’", 
    "capital": "", 
    "population": "69280", 
    "population_proper": "69280"
  }, 
  {
    "city": "Kovel", 
    "lat": "51.2167", 
    "lng": "24.7167", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Volyns’ka Oblast’", 
    "capital": "minor", 
    "population": "69089", 
    "population_proper": "69089"
  }, 
  {
    "city": "Smila", 
    "lat": "49.2167", 
    "lng": "31.8667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Cherkas’ka Oblast’", 
    "capital": "minor", 
    "population": "68536", 
    "population_proper": "68536"
  }, 
  {
    "city": "Kalush", 
    "lat": "49.0442", 
    "lng": "24.3597", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Ivano-Frankivs’ka Oblast’", 
    "capital": "minor", 
    "population": "66406", 
    "population_proper": "66406"
  }, 
  {
    "city": "Korosten", 
    "lat": "50.9500", 
    "lng": "28.6500", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zhytomyrs’ka Oblast’", 
    "capital": "minor", 
    "population": "63525", 
    "population_proper": "63525"
  }, 
  {
    "city": "Pokrovsk", 
    "lat": "48.2833", 
    "lng": "37.1833", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "minor", 
    "population": "63437", 
    "population_proper": "63437"
  }, 
  {
    "city": "Boryspil", 
    "lat": "50.3500", 
    "lng": "30.9500", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyivs’ka Oblast’", 
    "capital": "minor", 
    "population": "62281", 
    "population_proper": "62281"
  }, 
  {
    "city": "Kolomyia", 
    "lat": "48.5167", 
    "lng": "25.0333", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Ivano-Frankivs’ka Oblast’", 
    "capital": "minor", 
    "population": "61269", 
    "population_proper": "61269"
  }, 
  {
    "city": "Rubizhne", 
    "lat": "49.0167", 
    "lng": "38.3667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "59951", 
    "population_proper": "59951"
  }, 
  {
    "city": "Chornomorsk", 
    "lat": "46.3017", 
    "lng": "30.6569", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Odes’ka Oblast’", 
    "capital": "", 
    "population": "59800", 
    "population_proper": "59800"
  }, 
  {
    "city": "Khartsyzk", 
    "lat": "48.0333", 
    "lng": "38.1500", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "59763", 
    "population_proper": "59763"
  }, 
  {
    "city": "Druzhkivka", 
    "lat": "48.6203", 
    "lng": "37.5278", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "59400", 
    "population_proper": "59400"
  }, 
  {
    "city": "Stryi", 
    "lat": "49.2500", 
    "lng": "23.8500", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "L’vivs’ka Oblast’", 
    "capital": "minor", 
    "population": "59325", 
    "population_proper": "59325"
  }, 
  {
    "city": "Bilhorod-Dnistrovskyi", 
    "lat": "46.1833", 
    "lng": "30.3333", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Odes’ka Oblast’", 
    "capital": "minor", 
    "population": "57210", 
    "population_proper": "57210"
  }, 
  {
    "city": "Irpin", 
    "lat": "50.5167", 
    "lng": "30.2500", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyivs’ka Oblast’", 
    "capital": "", 
    "population": "56806", 
    "population_proper": "56806"
  }, 
  {
    "city": "Novohrad-Volynskyi", 
    "lat": "50.5833", 
    "lng": "27.6333", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zhytomyrs’ka Oblast’", 
    "capital": "minor", 
    "population": "56288", 
    "population_proper": "56288"
  }, 
  {
    "city": "Lozova", 
    "lat": "48.8892", 
    "lng": "36.3161", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kharkivs’ka Oblast’", 
    "capital": "minor", 
    "population": "55827", 
    "population_proper": "55827"
  }, 
  {
    "city": "Antratsyt", 
    "lat": "48.1167", 
    "lng": "39.0833", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "54640", 
    "population_proper": "54640"
  }, 
  {
    "city": "Enerhodar", 
    "lat": "47.4989", 
    "lng": "34.6558", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Zaporiz’ka Oblast’", 
    "capital": "minor", 
    "population": "53567", 
    "population_proper": "53567"
  }, 
  {
    "city": "Pryluky", 
    "lat": "50.6000", 
    "lng": "32.4000", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Chernihivs’ka Oblast’", 
    "capital": "minor", 
    "population": "53395", 
    "population_proper": "53395"
  }, 
  {
    "city": "Novovolynsk", 
    "lat": "50.7333", 
    "lng": "24.1667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Volyns’ka Oblast’", 
    "capital": "", 
    "population": "52188", 
    "population_proper": "52188"
  }, 
  {
    "city": "Horishni Plavni", 
    "lat": "49.0107", 
    "lng": "33.6562", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Poltavs’ka Oblast’", 
    "capital": "", 
    "population": "52167", 
    "population_proper": "52167"
  }, 
  {
    "city": "Myrnohrad", 
    "lat": "48.3022", 
    "lng": "37.2614", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "50360", 
    "population_proper": "50360"
  }, 
  {
    "city": "Shakhtarsk", 
    "lat": "48.0333", 
    "lng": "38.4833", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "minor", 
    "population": "49482", 
    "population_proper": "49482"
  }, 
  {
    "city": "Okhtyrka", 
    "lat": "50.3074", 
    "lng": "34.9016", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Sums’ka Oblast’", 
    "capital": "minor", 
    "population": "47971", 
    "population_proper": "47971"
  }, 
  {
    "city": "Brianka", 
    "lat": "48.5133", 
    "lng": "38.6431", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "47512", 
    "population_proper": "47512"
  }, 
  {
    "city": "Snizhne", 
    "lat": "48.0167", 
    "lng": "38.7667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Donets’ka Oblast’", 
    "capital": "", 
    "population": "47259", 
    "population_proper": "47259"
  }, 
  {
    "city": "Marhanets", 
    "lat": "47.6480", 
    "lng": "34.6167", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "minor", 
    "population": "47141", 
    "population_proper": "47141"
  }, 
  {
    "city": "Rovenky", 
    "lat": "48.0833", 
    "lng": "39.3667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "46734", 
    "population_proper": "46734"
  }, 
  {
    "city": "Fastiv", 
    "lat": "50.0747", 
    "lng": "29.9181", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyivs’ka Oblast’", 
    "capital": "minor", 
    "population": "45907", 
    "population_proper": "45907"
  }, 
  {
    "city": "Lubny", 
    "lat": "50.0186", 
    "lng": "32.9869", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Poltavs’ka Oblast’", 
    "capital": "minor", 
    "population": "45786", 
    "population_proper": "45786"
  }, 
  {
    "city": "Svitlovodsk", 
    "lat": "49.0833", 
    "lng": "33.2500", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kirovohrads’ka Oblast’", 
    "capital": "minor", 
    "population": "45312", 
    "population_proper": "45312"
  }, 
  {
    "city": "Zhovti Vody", 
    "lat": "48.3500", 
    "lng": "33.5167", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "", 
    "population": "44766", 
    "population_proper": "44766"
  }, 
  {
    "city": "Krasnodon", 
    "lat": "48.3000", 
    "lng": "39.7333", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "43683", 
    "population_proper": "43683"
  }, 
  {
    "city": "Shepetivka", 
    "lat": "50.1833", 
    "lng": "27.0667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Khmel’nyts’ka Oblast’", 
    "capital": "minor", 
    "population": "41415", 
    "population_proper": "41415"
  }, 
  {
    "city": "Vyshneve", 
    "lat": "50.3833", 
    "lng": "30.3667", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyivs’ka Oblast’", 
    "capital": "", 
    "population": "40919", 
    "population_proper": "40919"
  }, 
  {
    "city": "Romny", 
    "lat": "50.7428", 
    "lng": "33.4879", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Sums’ka Oblast’", 
    "capital": "minor", 
    "population": "40316", 
    "population_proper": "40316"
  }, 
  {
    "city": "Myrhorod", 
    "lat": "49.9640", 
    "lng": "33.6124", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Poltavs’ka Oblast’", 
    "capital": "minor", 
    "population": "40160", 
    "population_proper": "40160"
  }, 
  {
    "city": "Podilsk", 
    "lat": "47.7419", 
    "lng": "29.5350", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Odes’ka Oblast’", 
    "capital": "minor", 
    "population": "40155", 
    "population_proper": "40155"
  }, 
  {
    "city": "Pokrov", 
    "lat": "47.6632", 
    "lng": "34.0811", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Dnipropetrovs’ka Oblast’", 
    "capital": "", 
    "population": "39497", 
    "population_proper": "39497"
  }, 
  {
    "city": "Volodymyr-Volynskyi", 
    "lat": "50.8481", 
    "lng": "24.3222", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Volyns’ka Oblast’", 
    "capital": "minor", 
    "population": "38901", 
    "population_proper": "38901"
  }, 
  {
    "city": "Pervomaisk", 
    "lat": "48.6333", 
    "lng": "38.5167", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Luhans’ka Oblast’", 
    "capital": "", 
    "population": "38801", 
    "population_proper": "38801"
  }, 
  {
    "city": "Dzhankoi", 
    "lat": "45.7086", 
    "lng": "34.3933", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Krym, Avtonomna Respublika", 
    "capital": "minor", 
    "population": "38714", 
    "population_proper": "38714"
  }, 
  {
    "city": "Vasylkiv", 
    "lat": "50.1775", 
    "lng": "30.3217", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Kyyivs’ka Oblast’", 
    "capital": "", 
    "population": "37696", 
    "population_proper": "37696"
  }, 
  {
    "city": "Dubno", 
    "lat": "50.3931", 
    "lng": "25.7350", 
    "country": "Ukraine", 
    "iso2": "UA", 
    "admin_name": "Rivnens’ka Oblast’", 
    "capital": "minor", 
    "population": "37545", 
    "population_proper": "37545"
  }
]